name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - 'master'

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.4.0
        with:
          dockerfile: Dockerfile
